services:
    application_user.registration.form_type:
        class: Application\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_registration }

    application_user.profile.form_type:
        class: Application\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_profile }

    application_user.profile_listener:
        class: Application\UserBundle\EventListener\ProfileListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    application_user.user_subscriber:
        class: Application\UserBundle\EventListener\UserSubscriber
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setContainer, [@service_container] ]

    application_user.group_subscriber:
        class: Application\UserBundle\EventListener\GroupSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    application_user.admin_user:
        class: Application\UserBundle\Controller\AdminController
        tags:
            - { name: application_admin.dashboard }

    application_user.groups.group_type:
        class: Application\UserBundle\Form\Type\GroupType
        arguments: [%security.role_hierarchy.roles%, @translator]

    application_user.user_manager:
        class: Application\UserBundle\Manager\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]

    application_user.group_manager:
        class: Application\UserBundle\Manager\GroupManager
        arguments: [@fos_user.entity_manager, %fos_user.model.group.class%, @application_user.user_manager]
