security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: 
            - ROLE_ADMIN
            - ROLE_USER_ADMIN_USERS
            - ROLE_FORUM_MODERATE
        
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:         ^/
            form_login:
                provider:    fos_userbundle
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                remember_me: true
                csrf_provider:  form.csrf_provider
                
            remember_me:
                key:         "%secret%"
                lifetime:    3600
                path:        /
                
            logout:
                path:        fos_user_security_logout
                target:      /
                
            anonymous:       true

    access_control:
        - { path: ^(/(%route_locale_requirements%)/login)|(/login)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%route_locale_requirements%)/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%route_locale_requirements%)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%route_locale_requirements%)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/(%route_locale_requirements%)/user/, role: IS_AUTHENTICATED_FULLY }

    